-- User-defined list of LaTeX macros
local macrolist = {
  'Alpha',
  'Beta',
  'C',
  'Delta',
  'Epsilon',
  'Eta',
  'Gal',
  'Gamma',
  'Hom',
  'Lambda',
  'Leftarrow',
  'Leftrightarrow',
  'Mu',
  'Nu',
  'Omega',
  'Phi',
  'Pi',
  'Psi',
  'Q',
  'Rho',
  'Rightarrow',
  'Sigma',
  'Spec',
  'Theta',
  'Xi',
  'Z',
  'Zeta',
  'alpha',
  'ar{dl}',
  'ar{dr}',
  'ar{d}',
  'ar{l}',
  'ar{r}',
  'ar{ul}',
  'ar{ur}',
  'ar{u}',
  'beta',
  'bigoplus',
  'cdot',
  'cong',
  'delta',
  'dim',
  'emptyset',
  'epsilon',
  'eta',
  'gamma',
  'in',
  'lambda',
  'left',
  'mapsto',
  'mathrm{',
  'mb', -- mathbb
  'mc', -- mathcal
  'mf', -- mathfrak
  'mu',
  'nu',
  'omega',
  'oplus',
  'otimes',
  'overline{',
  'partial',
  'phi',
  'pi',
  'prod_{',
  'psi',
  'rho',
  'right',
  'section{',
  'sharp',
  'sigma',
  'sim',
  'subsection{',
  'subset',
  'subseteq',
  'subsubsection{', 
  'sum_{',
  'supset',
  'supseteq',
  'text{',
  'textbf{',
  'textit{',
  'theta',
  'times',
  'to',
  'underline{',
  'varepsilon',
  'varnothing',
  'varphi',
  'wedge',
  'xi',
  'xrightarrow{',
  'zeta',
  -- Add more macros as needed
}

-- User-defined custom shorthands
local custom_shorthands = {
  varphi = 'vph',
  vartheta = 'vth',
  varsigma = 'vsg',
  varnothing = 'vno',
  subset = 'sb',
  supset = 'sp',
  -- Add more custom shorthands as needed
}

-- Function to compute minimal unique prefixes
local function compute_min_unique_prefixes(macros)
  local prefixes = {}
  for _, macro in ipairs(macros) do
    -- Use custom shorthand if available
    if custom_shorthands[macro] then
      prefixes[macro] = custom_shorthands[macro]
    else
      local min_prefix = macro
      for i = 1, #macro do
        local prefix = macro:sub(1, i)
        local unique = true
        for _, other_macro in ipairs(macros) do
          if other_macro ~= macro and other_macro:sub(1, i) == prefix then
            unique = false
            break
          end
        end
        if unique then
          min_prefix = prefix
          break
        end
      end
      prefixes[macro] = min_prefix
    end
  end
  return prefixes
end

-- Compute minimal unique prefixes
local prefixes = compute_min_unique_prefixes(macrolist)

-- Create a mapping of abbreviations to their expansions
function latex_shortcuts_new()
  -- local abbrev_map = {}
  -- for macro, mup in pairs(prefixes) do
  --   abbrev_map[';' .. mup] = '\\' .. macro
  --   vim.api.nvim_set_keymap('i', ';' .. mup, '\\' .. macro, { noremap = true, silent = true })
  -- end
  latex_shortcuts_ext()
  vim.api.nvim_set_keymap('i', ';-1', '^{-1}', { noremap = true, silent = true })
  vim.api.nvim_set_keymap('i', ';2', '^2', { noremap = true, silent = true })
  vim.api.nvim_set_keymap('i', ';^', '^{}<ESC>i', { noremap = true, silent = true })
end

-- Set the autocmd to apply this only in LaTeX files
vim.api.nvim_exec([[
  augroup LaTeXShortcuts
    autocmd!
    autocmd FileType tex lua latex_shortcuts_new()
    autocmd FileType markdown lua latex_shortcuts_new()
  augroup END
]], false)

function latex_shortcuts_ext()
  vim.api.nvim_set_keymap('i', ';A', '\\Alpha', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';B', '\\Beta', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';C', '\\C', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';D', '\\Delta', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Ea', '\\Ea', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Eb', '\\Eb', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Ec', '\\Ec', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Ed', '\\Ed', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Ee', '\\Ee', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Ef', '\\Ef', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Eg', '\\Eg', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Eh', '\\Eh', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Ei', '\\Ei', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Ej', '\\Ej', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Ek', '\\Ek', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';El', '\\El', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Em', '\\Em', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';En', '\\En', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Eo', '\\Eo', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Ep', '\\Epsilon', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Eq', '\\Eq', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Er', '\\Er', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Es', '\\Es', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Et', '\\Eta', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Eu', '\\Eu', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Ev', '\\Ev', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Ew', '\\Ew', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Ex', '\\Ex', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Ey', '\\Ey', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Ez', '\\Ez', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gaa', '\\Gaa', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gab', '\\Gab', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gac', '\\Gac', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gad', '\\Gad', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gae', '\\Gae', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gaf', '\\Gaf', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gag', '\\Gag', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gah', '\\Gah', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gai', '\\Gai', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gaj', '\\Gaj', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gak', '\\Gak', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gal', '\\Gal', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gam', '\\Gamma', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gan', '\\Gan', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gao', '\\Gao', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gap', '\\Gap', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gaq', '\\Gaq', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gar', '\\Gar', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gas', '\\Gas', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gat', '\\Gat', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gau', '\\Gau', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gav', '\\Gav', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gaw', '\\Gaw', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gax', '\\Gax', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gay', '\\Gay', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gaz', '\\Gaz', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gb', '\\Gb', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gc', '\\Gc', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gd', '\\Gd', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Ge', '\\Ge', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gf', '\\Gf', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gg', '\\Gg', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gh', '\\Gh', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gi', '\\Gi', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gj', '\\Gj', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gk', '\\Gk', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gl', '\\Gl', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gm', '\\Gm', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gn', '\\Gn', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Go', '\\Go', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gp', '\\Gp', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gq', '\\Gq', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gr', '\\Gr', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gs', '\\Gs', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gt', '\\Gt', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gu', '\\Gu', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gv', '\\Gv', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gw', '\\Gw', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gx', '\\Gx', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gy', '\\Gy', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Gz', '\\Gz', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';H', '\\Hom', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';La', '\\Lambda', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lb', '\\Lb', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lc', '\\Lc', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Ld', '\\Ld', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lea', '\\Lea', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Leb', '\\Leb', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lec', '\\Lec', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Led', '\\Led', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lee', '\\Lee', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lefa', '\\Lefa', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lefb', '\\Lefb', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lefc', '\\Lefc', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lefd', '\\Lefd', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lefe', '\\Lefe', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Leff', '\\Leff', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lefg', '\\Lefg', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lefh', '\\Lefh', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lefi', '\\Lefi', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lefj', '\\Lefj', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lefk', '\\Lefk', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lefl', '\\Lefl', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lefm', '\\Lefm', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lefn', '\\Lefn', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lefo', '\\Lefo', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lefp', '\\Lefp', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lefq', '\\Lefq', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lefr', '\\Lefr', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lefs', '\\Lefs', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lefta', '\\Leftarrow', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Leftb', '\\Leftb', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Leftc', '\\Leftc', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Leftd', '\\Leftd', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lefte', '\\Lefte', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Leftf', '\\Leftf', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Leftg', '\\Leftg', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lefth', '\\Lefth', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lefti', '\\Lefti', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Leftj', '\\Leftj', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Leftk', '\\Leftk', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Leftl', '\\Leftl', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Leftm', '\\Leftm', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Leftn', '\\Leftn', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lefto', '\\Lefto', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Leftp', '\\Leftp', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Leftq', '\\Leftq', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Leftr', '\\Leftrightarrow', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lefts', '\\Lefts', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Leftt', '\\Leftt', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Leftu', '\\Leftu', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Leftv', '\\Leftv', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Leftw', '\\Leftw', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Leftx', '\\Leftx', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lefty', '\\Lefty', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Leftz', '\\Leftz', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lefu', '\\Lefu', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lefv', '\\Lefv', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lefw', '\\Lefw', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lefx', '\\Lefx', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lefy', '\\Lefy', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lefz', '\\Lefz', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Leg', '\\Leg', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Leh', '\\Leh', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lei', '\\Lei', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lej', '\\Lej', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lek', '\\Lek', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lel', '\\Lel', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lem', '\\Lem', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Len', '\\Len', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Leo', '\\Leo', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lep', '\\Lep', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Leq', '\\Leq', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Ler', '\\Ler', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Les', '\\Les', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Let', '\\Let', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Leu', '\\Leu', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lev', '\\Lev', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lew', '\\Lew', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lex', '\\Lex', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Ley', '\\Ley', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lez', '\\Lez', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lf', '\\Lf', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lg', '\\Lg', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lh', '\\Lh', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Li', '\\Li', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lj', '\\Lj', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lk', '\\Lk', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Ll', '\\Ll', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lm', '\\Lm', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Ln', '\\Ln', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lo', '\\Lo', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lp', '\\Lp', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lq', '\\Lq', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lr', '\\Lr', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Ls', '\\Ls', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lt', '\\Lt', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lu', '\\Lu', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lv', '\\Lv', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lw', '\\Lw', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lx', '\\Lx', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Ly', '\\Ly', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Lz', '\\Lz', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';M', '\\Mu', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';N', '\\Nu', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';O', '\\Omega', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Pa', '\\Pa', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Pb', '\\Pb', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Pc', '\\Pc', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Pd', '\\Pd', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Pe', '\\Pe', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Pf', '\\Pf', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Pg', '\\Pg', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Ph', '\\Phi', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Pi', '\\Pi', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Pj', '\\Pj', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Pk', '\\Pk', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Pl', '\\Pl', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Pm', '\\Pm', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Pn', '\\Pn', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Po', '\\Po', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Pp', '\\Pp', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Pq', '\\Pq', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Pr', '\\Pr', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Ps', '\\Psi', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Pt', '\\Pt', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Pu', '\\Pu', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Pv', '\\Pv', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Pw', '\\Pw', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Px', '\\Px', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Py', '\\Py', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Pz', '\\Pz', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Q', '\\Q', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Ra', '\\Ra', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Rb', '\\Rb', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Rc', '\\Rc', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Rd', '\\Rd', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Re', '\\Re', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Rf', '\\Rf', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Rg', '\\Rg', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Rh', '\\Rho', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Ri', '\\Rightarrow', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Rj', '\\Rj', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Rk', '\\Rk', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Rl', '\\Rl', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Rm', '\\Rm', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Rn', '\\Rn', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Ro', '\\Ro', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Rp', '\\Rp', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Rq', '\\Rq', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Rr', '\\Rr', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Rs', '\\Rs', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Rt', '\\Rt', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Ru', '\\Ru', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Rv', '\\Rv', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Rw', '\\Rw', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Rx', '\\Rx', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Ry', '\\Ry', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Rz', '\\Rz', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Sa', '\\Sa', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Sb', '\\Sb', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Sc', '\\Sc', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Sd', '\\Sd', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Se', '\\Se', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Sf', '\\Sf', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Sg', '\\Sg', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Sh', '\\Sh', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Si', '\\Sigma', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Sj', '\\Sj', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Sk', '\\Sk', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Sl', '\\Sl', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Sm', '\\Sm', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Sn', '\\Sn', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';So', '\\So', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Sp', '\\Spec', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Sq', '\\Sq', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Sr', '\\Sr', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Ss', '\\Ss', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';St', '\\St', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Su', '\\Su', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Sv', '\\Sv', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Sw', '\\Sw', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Sx', '\\Sx', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Sy', '\\Sy', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Sz', '\\Sz', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';T', '\\Theta', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';X', '\\Xi', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';Z', '\\Z', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';aa', '\\aa', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ab', '\\ab', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ac', '\\ac', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ad', '\\ad', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ae', '\\ae', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';af', '\\af', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ag', '\\ag', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ah', '\\ah', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ai', '\\ai', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';aj', '\\aj', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ak', '\\ak', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';al', '\\alpha', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';am', '\\am', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';an', '\\an', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ao', '\\ao', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ap', '\\ap', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';aq', '\\aq', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ara', '\\ara', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';arb', '\\arb', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';arc', '\\arc', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ard', '\\ard', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';are', '\\are', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';arf', '\\arf', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';arg', '\\arg', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';arh', '\\arh', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ari', '\\ari', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';arj', '\\arj', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ark', '\\ark', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';arl', '\\arl', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';arm', '\\arm', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';arn', '\\arn', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';aro', '\\aro', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';arp', '\\arp', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';arq', '\\arq', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';arr', '\\arr', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ars', '\\ars', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';art', '\\art', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';aru', '\\aru', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';arv', '\\arv', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';arw', '\\arw', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';arx', '\\arx', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ary', '\\ary', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';arz', '\\arz', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{a', '\\ar{a', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{b', '\\ar{b', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{c', '\\ar{c', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{da', '\\ar{da', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{db', '\\ar{db', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{dc', '\\ar{dc', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{dd', '\\ar{dd', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{de', '\\ar{de', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{df', '\\ar{df', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{dg', '\\ar{dg', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{dh', '\\ar{dh', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{di', '\\ar{di', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{dj', '\\ar{dj', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{dk', '\\ar{dk', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{dl', '\\ar{dl}', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{dm', '\\ar{dm', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{dn', '\\ar{dn', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{do', '\\ar{do', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{dp', '\\ar{dp', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{dq', '\\ar{dq', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{dr', '\\ar{dr}', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{ds', '\\ar{ds', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{dt', '\\ar{dt', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{du', '\\ar{du', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{dv', '\\ar{dv', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{dw', '\\ar{dw', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{dx', '\\ar{dx', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{dy', '\\ar{dy', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{dz', '\\ar{dz', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{d}', '\\ar{d}', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{e', '\\ar{e', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{f', '\\ar{f', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{g', '\\ar{g', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{h', '\\ar{h', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{i', '\\ar{i', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{j', '\\ar{j', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{k', '\\ar{k', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{l', '\\ar{l}', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{m', '\\ar{m', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{n', '\\ar{n', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{o', '\\ar{o', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{p', '\\ar{p', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{q', '\\ar{q', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{r', '\\ar{r}', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{s', '\\ar{s', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{t', '\\ar{t', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{ua', '\\ar{ua', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{ub', '\\ar{ub', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{uc', '\\ar{uc', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{ud', '\\ar{ud', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{ue', '\\ar{ue', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{uf', '\\ar{uf', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{ug', '\\ar{ug', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{uh', '\\ar{uh', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{ui', '\\ar{ui', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{uj', '\\ar{uj', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{uk', '\\ar{uk', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{ul', '\\ar{ul}', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{um', '\\ar{um', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{un', '\\ar{un', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{uo', '\\ar{uo', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{up', '\\ar{up', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{uq', '\\ar{uq', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{ur', '\\ar{ur}', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{us', '\\ar{us', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{ut', '\\ar{ut', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{uu', '\\ar{uu', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{uv', '\\ar{uv', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{uw', '\\ar{uw', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{ux', '\\ar{ux', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{uy', '\\ar{uy', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{uz', '\\ar{uz', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{u}', '\\ar{u}', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{v', '\\ar{v', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{w', '\\ar{w', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{x', '\\ar{x', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{y', '\\ar{y', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ar{z', '\\ar{z', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';as', '\\as', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';at', '\\at', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';au', '\\au', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';av', '\\av', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';aw', '\\aw', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ax', '\\ax', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ay', '\\ay', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';az', '\\az', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ba', '\\ba', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';bb', '\\bb', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';bc', '\\bc', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';bd', '\\bd', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';be', '\\beta', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';bf', '\\bf', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';bg', '\\bg', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';bh', '\\bh', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';bi', '\\bigoplus', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';bj', '\\bj', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';bk', '\\bk', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';bl', '\\bl', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';bm', '\\bm', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';bn', '\\bn', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';bo', '\\bo', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';bp', '\\bp', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';bq', '\\bq', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';br', '\\br', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';bs', '\\bs', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';bt', '\\bt', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';bu', '\\bu', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';bv', '\\bv', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';bw', '\\bw', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';bx', '\\bx', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';by', '\\by', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';bz', '\\bz', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ca', '\\ca', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';cb', '\\cb', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';cc', '\\cc', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';cd', '\\cdot', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ce', '\\ce', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';cf', '\\cf', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';cg', '\\cg', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ch', '\\ch', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ci', '\\ci', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';cj', '\\cj', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ck', '\\ck', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';cl', '\\cl', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';cm', '\\cm', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';cn', '\\cn', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';co', '\\cong', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';cp', '\\cp', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';cq', '\\cq', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';cr', '\\cr', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';cs', '\\cs', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ct', '\\ct', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';cu', '\\cu', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';cv', '\\cv', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';cw', '\\cw', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';cx', '\\cx', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';cy', '\\cy', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';cz', '\\cz', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';da', '\\da', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';db', '\\db', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';dc', '\\dc', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';dd', '\\dd', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';de', '\\delta', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';df', '\\df', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';dg', '\\dg', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';dh', '\\dh', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';di', '\\dim', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';dj', '\\dj', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';dk', '\\dk', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';dl', '\\dl', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';dm', '\\dm', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';dn', '\\dn', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';do', '\\do', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';dp', '\\dp', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';dq', '\\dq', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';dr', '\\dr', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ds', '\\ds', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';dt', '\\dt', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';du', '\\du', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';dv', '\\dv', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';dw', '\\dw', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';dx', '\\dx', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';dy', '\\dy', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';dz', '\\dz', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ea', '\\ea', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';eb', '\\eb', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ec', '\\ec', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ed', '\\ed', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ee', '\\ee', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ef', '\\ef', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';eg', '\\eg', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';eh', '\\eh', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ei', '\\ei', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ej', '\\ej', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ek', '\\ek', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';el', '\\el', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';em', '\\emptyset', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';en', '\\en', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';eo', '\\eo', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ep', '\\epsilon', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';eq', '\\eq', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';er', '\\er', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';es', '\\es', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';et', '\\eta', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';eu', '\\eu', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ev', '\\ev', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ew', '\\ew', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ex', '\\ex', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ey', '\\ey', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ez', '\\ez', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';f', '\\f', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';g', '\\gamma', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';h', '\\h', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';i', '\\in', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';j', '\\j', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';k', '\\k', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';la', '\\lambda', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';lb', '\\lb', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';lc', '\\lc', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ld', '\\ld', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';le', '\\left', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';lf', '\\lf', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';lg', '\\lg', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';lh', '\\lh', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';li', '\\li', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';lj', '\\lj', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';lk', '\\lk', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ll', '\\ll', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';lm', '\\lm', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ln', '\\ln', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';lo', '\\lo', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';lp', '\\lp', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';lq', '\\lq', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';lr', '\\lr', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ls', '\\ls', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';lt', '\\lt', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';lu', '\\lu', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';lv', '\\lv', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';lw', '\\lw', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';lx', '\\lx', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ly', '\\ly', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';lz', '\\lz', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';maa', '\\maa', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';mab', '\\mab', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';mac', '\\mac', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';mad', '\\mad', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';mae', '\\mae', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';maf', '\\maf', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';mag', '\\mag', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';mah', '\\mah', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';mai', '\\mai', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';maj', '\\maj', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';mak', '\\mak', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';mal', '\\mal', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';mam', '\\mam', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';man', '\\man', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';mao', '\\mao', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';map', '\\mapsto', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';maq', '\\maq', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';mar', '\\mar', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';mas', '\\mas', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';mat', '\\mathrm{', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';mau', '\\mau', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';mav', '\\mav', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';maw', '\\maw', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';max', '\\max', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';may', '\\may', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';maz', '\\maz', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';mb', '\\mb', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';mc', '\\mc', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';md', '\\md', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';me', '\\me', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';mf', '\\mf', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';mg', '\\mg', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';mh', '\\mh', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';mi', '\\mi', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';mj', '\\mj', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';mk', '\\mk', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ml', '\\ml', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';mm', '\\mm', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';mn', '\\mn', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';mo', '\\mo', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';mp', '\\mp', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';mq', '\\mq', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';mr', '\\mr', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ms', '\\ms', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';mt', '\\mt', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';mu', '\\mu', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';mv', '\\mv', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';mw', '\\mw', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';mx', '\\mx', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';my', '\\my', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';mz', '\\mz', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';n', '\\nu', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';oa', '\\oa', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ob', '\\ob', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';oc', '\\oc', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';od', '\\od', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';oe', '\\oe', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';of', '\\of', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';og', '\\og', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';oh', '\\oh', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';oi', '\\oi', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';oj', '\\oj', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ok', '\\ok', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ol', '\\ol', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';om', '\\omega', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';on', '\\on', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';oo', '\\oo', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';op', '\\oplus', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';oq', '\\oq', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';or', '\\or', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';os', '\\os', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ot', '\\otimes', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ou', '\\ou', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ov', '\\overline{', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ow', '\\ow', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ox', '\\ox', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';oy', '\\oy', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';oz', '\\oz', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';pa', '\\partial', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';pb', '\\pb', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';pc', '\\pc', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';pd', '\\pd', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';pe', '\\pe', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';pf', '\\pf', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';pg', '\\pg', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ph', '\\phi', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';pi', '\\pi', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';pj', '\\pj', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';pk', '\\pk', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';pl', '\\pl', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';pm', '\\pm', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';pn', '\\pn', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';po', '\\po', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';pp', '\\pp', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';pq', '\\pq', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';pr', '\\prod_{', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ps', '\\psi', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';pt', '\\pt', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';pu', '\\pu', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';pv', '\\pv', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';pw', '\\pw', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';px', '\\px', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';py', '\\py', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';pz', '\\pz', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';q', '\\q', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ra', '\\ra', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';rb', '\\rb', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';rc', '\\rc', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';rd', '\\rd', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';re', '\\re', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';rf', '\\rf', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';rg', '\\rg', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';rh', '\\rho', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ri', '\\right', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';rj', '\\rj', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';rk', '\\rk', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';rl', '\\rl', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';rm', '\\rm', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';rn', '\\rn', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ro', '\\ro', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';rp', '\\rp', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';rq', '\\rq', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';rr', '\\rr', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';rs', '\\rs', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';rt', '\\rt', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ru', '\\ru', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';rv', '\\rv', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';rw', '\\rw', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';rx', '\\rx', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ry', '\\ry', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';rz', '\\rz', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sa', '\\sa', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sb', '\\sb', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sc', '\\sc', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sd', '\\sd', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';se', '\\section{', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sf', '\\sf', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sg', '\\sg', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sh', '\\sharp', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sia', '\\sia', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sib', '\\sib', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sic', '\\sic', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sid', '\\sid', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sie', '\\sie', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sif', '\\sif', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sig', '\\sigma', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sih', '\\sih', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sii', '\\sii', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sij', '\\sij', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sik', '\\sik', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sil', '\\sil', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sim', '\\sim', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sin', '\\sin', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sio', '\\sio', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sip', '\\sip', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';siq', '\\siq', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sir', '\\sir', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sis', '\\sis', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sit', '\\sit', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';siu', '\\siu', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';siv', '\\siv', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';siw', '\\siw', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';six', '\\six', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';siy', '\\siy', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';siz', '\\siz', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sj', '\\sj', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sk', '\\sk', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sl', '\\sl', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sm', '\\sm', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sn', '\\sn', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';so', '\\so', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sp', '\\sp', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sq', '\\sq', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sr', '\\sr', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ss', '\\ss', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';st', '\\st', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sua', '\\sua', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';suba', '\\suba', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subb', '\\subb', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subc', '\\subc', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subd', '\\subd', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sube', '\\sube', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subf', '\\subf', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subg', '\\subg', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subh', '\\subh', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subi', '\\subi', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subj', '\\subj', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subk', '\\subk', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subl', '\\subl', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subm', '\\subm', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subn', '\\subn', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subo', '\\subo', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subp', '\\subp', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subq', '\\subq', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subr', '\\subr', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subsa', '\\subsa', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subsb', '\\subsb', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subsc', '\\subsc', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subsd', '\\subsd', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subsea', '\\subsea', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subseb', '\\subseb', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subsec', '\\subsection{', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subsed', '\\subsed', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subsee', '\\subsee', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subsef', '\\subsef', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subseg', '\\subseg', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subseh', '\\subseh', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subsei', '\\subsei', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subsej', '\\subsej', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subsek', '\\subsek', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subsel', '\\subsel', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subsem', '\\subsem', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subsen', '\\subsen', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subseo', '\\subseo', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subsep', '\\subsep', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subseq', '\\subseq', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subser', '\\subser', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subses', '\\subses', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subset', '\\subset', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subseu', '\\subseu', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subsev', '\\subsev', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subsew', '\\subsew', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subsex', '\\subsex', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subsey', '\\subsey', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subsez', '\\subsez', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subsf', '\\subsf', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subsg', '\\subsg', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subsh', '\\subsh', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subsi', '\\subsi', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subsj', '\\subsj', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subsk', '\\subsk', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subsl', '\\subsl', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subsm', '\\subsm', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subsn', '\\subsn', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subso', '\\subso', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subsp', '\\subsp', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subsq', '\\subsq', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subsr', '\\subsr', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subss', '\\subss', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subst', '\\subst', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subsu', '\\subsubsection{', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subsv', '\\subsv', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subsw', '\\subsw', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subsx', '\\subsx', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subsy', '\\subsy', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subsz', '\\subsz', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subt', '\\subt', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subu', '\\subu', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subv', '\\subv', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subw', '\\subw', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subx', '\\subx', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';suby', '\\suby', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';subz', '\\subz', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';suc', '\\suc', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sud', '\\sud', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sue', '\\sue', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';suf', '\\suf', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sug', '\\sug', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';suh', '\\suh', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sui', '\\sui', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';suj', '\\suj', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';suk', '\\suk', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sul', '\\sul', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sum', '\\sum_{', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sun', '\\sun', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';suo', '\\suo', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supa', '\\supa', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supb', '\\supb', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supc', '\\supc', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supd', '\\supd', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supe', '\\supe', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supf', '\\supf', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supg', '\\supg', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';suph', '\\suph', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supi', '\\supi', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supj', '\\supj', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supk', '\\supk', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supl', '\\supl', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supm', '\\supm', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supn', '\\supn', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supo', '\\supo', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supp', '\\supp', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supq', '\\supq', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supr', '\\supr', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supsa', '\\supsa', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supsb', '\\supsb', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supsc', '\\supsc', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supsd', '\\supsd', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supsea', '\\supsea', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supseb', '\\supseb', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supsec', '\\supsec', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supsed', '\\supsed', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supsee', '\\supsee', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supsef', '\\supsef', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supseg', '\\supseg', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supseh', '\\supseh', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supsei', '\\supsei', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supsej', '\\supsej', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supsek', '\\supsek', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supsel', '\\supsel', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supsem', '\\supsem', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supsen', '\\supsen', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supseo', '\\supseo', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supsep', '\\supsep', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supseq', '\\supseq', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supser', '\\supser', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supses', '\\supses', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supset', '\\supset', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supseu', '\\supseu', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supsev', '\\supsev', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supsew', '\\supsew', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supsex', '\\supsex', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supsey', '\\supsey', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supsez', '\\supsez', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supsf', '\\supsf', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supsg', '\\supsg', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supsh', '\\supsh', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supsi', '\\supsi', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supsj', '\\supsj', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supsk', '\\supsk', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supsl', '\\supsl', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supsm', '\\supsm', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supsn', '\\supsn', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supso', '\\supso', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supsp', '\\supsp', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supsq', '\\supsq', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supsr', '\\supsr', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supss', '\\supss', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supst', '\\supst', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supsu', '\\supsu', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supsv', '\\supsv', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supsw', '\\supsw', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supsx', '\\supsx', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supsy', '\\supsy', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supsz', '\\supsz', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supt', '\\supt', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supu', '\\supu', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supv', '\\supv', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supw', '\\supw', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supx', '\\supx', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supy', '\\supy', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';supz', '\\supz', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';suq', '\\suq', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sur', '\\sur', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sus', '\\sus', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sut', '\\sut', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';suu', '\\suu', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';suv', '\\suv', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';suw', '\\suw', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sux', '\\sux', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';suy', '\\suy', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';suz', '\\suz', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sv', '\\sv', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sw', '\\sw', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sx', '\\sx', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sy', '\\sy', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';sz', '\\sz', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ta', '\\ta', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';tb', '\\tb', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';tc', '\\tc', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';td', '\\td', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';tea', '\\tea', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';teb', '\\teb', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';tec', '\\tec', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ted', '\\ted', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';tee', '\\tee', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';tef', '\\tef', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';teg', '\\teg', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';teh', '\\teh', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';tei', '\\tei', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';tej', '\\tej', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';tek', '\\tek', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';tel', '\\tel', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';tem', '\\tem', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ten', '\\ten', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';teo', '\\teo', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';tep', '\\tep', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';teq', '\\teq', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ter', '\\ter', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';tes', '\\tes', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';tet', '\\tet', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';teu', '\\teu', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';tev', '\\tev', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';tew', '\\tew', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';texa', '\\texa', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';texb', '\\texb', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';texc', '\\texc', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';texd', '\\texd', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';texe', '\\texe', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';texf', '\\texf', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';texg', '\\texg', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';texh', '\\texh', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';texi', '\\texi', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';texj', '\\texj', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';texk', '\\texk', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';texl', '\\texl', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';texm', '\\texm', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';texn', '\\texn', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';texo', '\\texo', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';texp', '\\texp', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';texq', '\\texq', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';texr', '\\texr', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';texs', '\\texs', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';texta', '\\texta', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';textb', '\\textbf{', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';textc', '\\textc', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';textd', '\\textd', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';texte', '\\texte', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';textf', '\\textf', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';textg', '\\textg', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';texth', '\\texth', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';texti', '\\textit{', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';textj', '\\textj', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';textk', '\\textk', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';textl', '\\textl', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';textm', '\\textm', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';textn', '\\textn', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';texto', '\\texto', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';textp', '\\textp', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';textq', '\\textq', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';textr', '\\textr', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';texts', '\\texts', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';textt', '\\textt', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';textu', '\\textu', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';textv', '\\textv', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';textw', '\\textw', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';textx', '\\textx', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';texty', '\\texty', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';textz', '\\textz', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';text{', '\\text{', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';texu', '\\texu', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';texv', '\\texv', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';texw', '\\texw', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';texx', '\\texx', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';texy', '\\texy', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';texz', '\\texz', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';tey', '\\tey', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';tez', '\\tez', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';tf', '\\tf', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';tg', '\\tg', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';th', '\\theta', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ti', '\\times', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';tj', '\\tj', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';tk', '\\tk', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';tl', '\\tl', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';tm', '\\tm', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';tn', '\\tn', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';to', '\\to', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';tp', '\\tp', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';tq', '\\tq', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';tr', '\\tr', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ts', '\\ts', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';tt', '\\tt', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';tu', '\\tu', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';tv', '\\tv', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';tw', '\\tw', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';tx', '\\tx', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ty', '\\ty', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';tz', '\\tz', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';u', '\\underline{', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vaa', '\\vaa', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vab', '\\vab', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vac', '\\vac', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vad', '\\vad', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vae', '\\vae', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vaf', '\\vaf', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vag', '\\vag', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vah', '\\vah', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vai', '\\vai', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vaj', '\\vaj', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vak', '\\vak', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';val', '\\val', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vam', '\\vam', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';van', '\\van', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vao', '\\vao', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vap', '\\vap', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vaq', '\\vaq', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vara', '\\vara', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';varb', '\\varb', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';varc', '\\varc', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vard', '\\vard', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vare', '\\varepsilon', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';varf', '\\varf', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';varg', '\\varg', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';varh', '\\varh', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vari', '\\vari', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';varj', '\\varj', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vark', '\\vark', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';varl', '\\varl', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';varm', '\\varm', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';varn', '\\varnothing', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';varo', '\\varo', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';varp', '\\varphi', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';varq', '\\varq', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';varr', '\\varr', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vars', '\\vars', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vart', '\\vart', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';varu', '\\varu', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';varv', '\\varv', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';varw', '\\varw', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';varx', '\\varx', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vary', '\\vary', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';varz', '\\varz', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vas', '\\vas', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vat', '\\vat', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vau', '\\vau', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vav', '\\vav', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vaw', '\\vaw', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vax', '\\vax', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vay', '\\vay', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vaz', '\\vaz', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vb', '\\vb', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vc', '\\vc', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vd', '\\vd', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';ve', '\\ve', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vf', '\\vf', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vg', '\\vg', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vh', '\\vh', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vi', '\\vi', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vj', '\\vj', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vk', '\\vk', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vl', '\\vl', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vm', '\\vm', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vn', '\\vn', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vo', '\\vo', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vp', '\\vp', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vq', '\\vq', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vr', '\\vr', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vs', '\\vs', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vt', '\\vt', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vu', '\\vu', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vv', '\\vv', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vw', '\\vw', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vx', '\\vx', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vy', '\\vy', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';vz', '\\vz', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';w', '\\wedge', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';xa', '\\xa', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';xb', '\\xb', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';xc', '\\xc', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';xd', '\\xd', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';xe', '\\xe', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';xf', '\\xf', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';xg', '\\xg', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';xh', '\\xh', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';xi', '\\xi', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';xj', '\\xj', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';xk', '\\xk', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';xl', '\\xl', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';xm', '\\xm', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';xn', '\\xn', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';xo', '\\xo', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';xp', '\\xp', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';xq', '\\xq', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';xr', '\\xrightarrow{', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';xs', '\\xs', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';xt', '\\xt', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';xu', '\\xu', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';xv', '\\xv', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';xw', '\\xw', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';xx', '\\xx', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';xy', '\\xy', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';xz', '\\xz', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';y', '\\y', {noremap = true, silent = true})
  vim.api.nvim_set_keymap('i', ';z', '\\zeta', {noremap = true, silent = true})
end

-- Function to expand abbreviations
--local function expand_abbrev()
--  local line = vim.api.nvim_get_current_line()
--  local cursor_col = vim.api.nvim_win_get_cursor(0)[2]
--  local col = cursor_col + 1  -- Lua index starts at 1
--
--  -- Find the start of the word before the cursor
--  local start_col = col
--  while start_col > 1 do
--    local c = line:sub(start_col - 1, start_col - 1)
--    if c:match('%s') then
--      break
--    end
--    start_col = start_col - 1
--  end
--
--  local prefix = line:sub(start_col, col)
--  local expansion = abbrev_map[prefix]
--
--  if expansion then
--    -- Replace the prefix with the expansion
--    vim.api.nvim_buf_set_text(0, vim.fn.line('.') - 1, start_col - 1, vim.fn.line('.') - 1, col, { expansion })
--    -- Move the cursor to the end of the expansion
--    vim.api.nvim_win_set_cursor(0, { vim.fn.line('.'), start_col - 1 + #expansion })
--    return ''
--  elseif prefix:sub(1,1) == ';' then
--    -- Unrecognized command starting with ';', replace ';' with '\'
--    local rest = prefix:sub(2)
--    local replacement = '\\' .. rest
--    vim.api.nvim_buf_set_text(0, vim.fn.line('.') - 1, start_col - 1, vim.fn.line('.') - 1, col, { replacement })
--    -- Move the cursor to the end of the replacement
--    vim.api.nvim_win_set_cursor(0, { vim.fn.line('.'), start_col - 1 + #replacement })
--    return ''
--  else
--    return ''
--  end
--end
--
---- Set up insert mode mappings for common trigger keys
--local opts = { expr = true, noremap = true }
--
--vim.api.nvim_set_keymap('i', '<Space>', 'v:lua.expand_abbrev() . " "', opts)
--vim.api.nvim_set_keymap('i', '<Tab>', 'v:lua.expand_abbrev() . "\\<Tab>"', opts)
--vim.api.nvim_set_keymap('i', '<CR>', 'v:lua.expand_abbrev() . "\\<CR>"', opts)
--vim.api.nvim_set_keymap('i', '.', 'v:lua.expand_abbrev() . "."', opts)
--vim.api.nvim_set_keymap('i', ',', 'v:lua.expand_abbrev() . ","', opts)
--vim.api.nvim_set_keymap('i', ';', 'v:lua.expand_abbrev() . ";"', opts)
